### PR TITLE
Add and update Thoth GitHub templates

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by codificat** [comment]
/lgtm

One side comment: AFAICT we don't have templates for pre or build release issues - not only in this repo, but in others. Kebechet does have the [ability to create these](https://github.com/thoth-station/kebechet/blob/4ed3a0fc8471800ea52b3267c24244225d732eba/kebechet/managers/version/version.py#L65-L73) though, so I'm wondering if we should start adding corresponding templates?
I understand that this means a growing list of templates though, potentially confusing... so I'm fine with leaving these out, it's only that I was wondering if it was an oversight

**Comment by fridex** [comment]
> /lgtm
> 
> One side comment: AFAICT we don't have templates for pre or build release issues - not only in this repo, but in others. Kebechet does have the [ability to create these](https://github.com/thoth-station/kebechet/blob/4ed3a0fc8471800ea52b3267c24244225d732eba/kebechet/managers/version/version.py#L65-L73) though, so I'm wondering if we should start adding corresponding templates? I understand that this means a growing list of templates though, potentially confusing... so I'm fine with leaving these out, it's only that I was wondering if it was an oversight

Initially, we did not include them - Pipenv has no ability to install pre-releases selectively only for some packages, hence we did not include them. These releases might be good for testing or very specific cases (like donkeycar), but it might be a good idea to stick with patch/minor/major releases for libs and components as we do at least for now.

**Comment by codificat** [comment]
Thanks, this makes sense.
I will leave it to @bjoernh2000 to /approve :slightly_smiling_face:

**Review by bjoernh2000 — APPROVED** [review]
/lgtm thank you! :100:

**Pull request merged**
