### PR TITLE
fixed import error

### PR DESCRIPTION
**Pull request by bjoernh2000**
## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Error with importing version that occurred after removing template.py, now import from version

## Description

Need this fix to run

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
It might be cleaner to move the version identifier to `app.py` and remove `version.py` file.

**Comment by bjoernh2000** [comment]
> It might be cleaner to move the version identifier to `app.py` and remove `version.py` file.

Will Kebechet automatically update app.py if `__version__ = '0.1.1'` is in `app.py` instead of `version.py` when creating new patches?

**Comment by fridex** [comment]
> > It might be cleaner to move the version identifier to `app.py` and remove `version.py` file.
> 
> Will Kebechet automatically update app.py if `__version__ = '0.1.1'` is in `app.py` instead of `version.py` when creating new patches?

Yes, it checks the following files: setup.py, version.py, __about.py, __init__.py, app.py and wsgi.py. It is stated in docs, but they are not rendered as of now.

**Comment by bjoernh2000** [comment]
> > > It might be cleaner to move the version identifier to `app.py` and remove `version.py` file.
> > 
> > 
> > Will Kebechet automatically update app.py if `__version__ = '0.1.1'` is in `app.py` instead of `version.py` when creating new patches?
> 
> Yes, it checks the following files: setup.py, version.py, __about.py, **init**.py, app.py and wsgi.py. It is stated in docs, but they are not rendered as of now.

Okay! Will add this asap

**Review by fridex — APPROVED** [review]
lgtm, thanks! 👍🏻

**Pull request merged**
